/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Curso;
import model.dao.CursoDAO;

/**
 *
 * @author Elton Sola
 */
public class DeleteCurso extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroCurso
     */
    public DeleteCurso() {
        initComponents();
        DefaultTableModel dmtCursos = (DefaultTableModel) jTCursos.getModel(); // usamos o DefaultTableModel para armazenar os objetos em vetores
        jTCursos.setRowSorter(new TableRowSorter(dmtCursos));
        
        readAlteraCurso();
    }
    
    public void readAlteraCurso(){
        DefaultTableModel dmtCursos = (DefaultTableModel) jTCursos.getModel();
        dmtCursos.setNumRows(0); // Seta o número de linhas como 0 para não cadastrar na lista duas vezes os mesmos dados
        CursoDAO cdao = new CursoDAO();
        
        for(Curso c: cdao.findAll()){ // Percorremos o objeto setando a lista findAll no Curso 
            
            dmtCursos.addRow(new Object[]{ //Passamos os valores vindo do banco de dados nesse vetor
                c.getCodigo(),
                c.getDescricao(),
                c.getEmenta()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCurso = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCursos = new javax.swing.JTable();

        setClosable(true);
        setResizable(true);
        setTitle("Deletar Curso");

        jLabel1.setText("Deletar Curso");

        jButton1.setText("Deletar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Ementa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTCursosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTCursos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(272, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(jTCursos.getSelectedRow() != -1){ // se for diferente de -1, foi selecionado alguma linha na lista
            Curso a = new Curso();
            CursoDAO dao = new CursoDAO();
            a.setDescricao(txtCurso.getText());
            a.setCodigo((int)jTCursos.getValueAt(jTCursos.getSelectedRow(), 0)); 
            dao.delete(a);

            txtCurso.setText(""); //limpar campo após cadastrar
            
            readAlteraCurso();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um curso para excluir");
        }  
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTCursosMouseClicked
        
        if(jTCursos.getSelectedRow() != -1){
                                                       //selecionando linha , (1) referente a coluna
            txtCurso.setText(jTCursos.getValueAt(jTCursos.getSelectedRow(), 1).toString());
            
        }
        
    }//GEN-LAST:event_jTCursosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTCursos;
    private javax.swing.JTextField txtCurso;
    // End of variables declaration//GEN-END:variables
}
