/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Aluno;
import model.bean.Curso_aluno;
import model.dao.AlunoDAO;
import model.dao.Curso_alunoDAO;

/**
 *
 * @author Elton Sola
 */
public class DeleteMatriculaCurso extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroCurso
     */
    public DeleteMatriculaCurso() {
        initComponents();
        DefaultTableModel dmtAlunos = (DefaultTableModel) jTNomes.getModel();
        jTNomes.setRowSorter(new TableRowSorter(dmtAlunos));
        
        readMatriculaCurso();
    }
    
    public void readMatriculaCurso(){
        DefaultTableModel dmtMatricula = (DefaultTableModel) jTNomes.getModel();
        dmtMatricula.setNumRows(0); // Seta o número de linhas como 0 para não cadastrar na lista duas vezes os mesmos dados
        Curso_alunoDAO cadao = new Curso_alunoDAO();
        
        for(Curso_aluno ca: cadao.findAll()){ // Percorremos o objeto setando a lista findAll no Curso 
            
            dmtMatricula.addRow(new Object[]{ //Passamos os valores vindo do banco de dados nesse vetor
                ca.getCodigo(),
                ca.getAluno(),
                ca.getCurso()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTNomes = new javax.swing.JTable();

        setClosable(true);
        setTitle("Deletar Matrícula Curso");

        jButton1.setText("Deletar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTNomes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código da Matrícula", "Nome do Aluno", "Nome do Curso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTNomes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTNomesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTNomes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 348, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        if(jTNomes.getSelectedRow() != -1){ // se for diferente de -1, foi selecionado alguma linha na lista
            
            Curso_alunoDAO cadao = new Curso_alunoDAO();
           
            int matricula = (int)jTNomes.getValueAt(jTNomes.getSelectedRow(), 0);
            Curso_aluno ca = cadao.findId(matricula);            
            
            cadao.deleteCurso(ca);
                    
            readMatriculaCurso();
         } else {
            JOptionPane.showMessageDialog(null, "Selecione uma matrícula para excluir");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTNomesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTNomesMouseClicked

    }//GEN-LAST:event_jTNomesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTNomes;
    // End of variables declaration//GEN-END:variables
}
